### ISSUE TITLE
No Activity found to handle Intent { act=android.intent.action.VIEW dat=mailto:xxxxxxxxxxxxxxxx@xxxxx.xxx (has extras) }

### ISSUE THREAD

**Issue by Jayin** [EManual/EManual-Android#40]
```
#1601	03-01 16:12:05.899	10178	E	AndroidRuntime	 FATAL EXCEPTION: main
#1602	03-01 16:12:05.899	10178	E	AndroidRuntime	 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=mailto:xxxxxxxxxxxxxxxx@xxxxx.xxx (has extras) }
#1603	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1512)
#1604	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1384)
#1605	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.app.Activity.startActivityForResult(Activity.java:3191)
#1606	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:817)
#1607	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.app.Activity.startActivity(Activity.java:3298)
#1608	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.text.style.URLSpan.onClick(URLSpan.java:62)
#1609	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:212)
#1610	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.widget.TextView.onTouchEvent(TextView.java:8346)
#1611	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.View.dispatchTouchEvent(View.java:5541)
#1612	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
#1613	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
#1614	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
#1615	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
#1616	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
#1617	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
#1618	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
#1619	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
#1620	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
#1621	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
#1622	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
#1623	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
#1624	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
#1625	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
#1626	03-01 16:12:05.899	10178	E	AndroidRuntime	         at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1915)
#1627	03-01 16:12:05.899	10178	E	AndroidRuntime	         at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1374)
#1628	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.app.Activity.dispatchTouchEvent(Activity.java:2365)
#1629	03-01 16:12:05.899	10178	E	AndroidRuntime	         at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1863)
#1630	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.View.dispatchPointerEvent(View.java:5721)
#1631	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2901)
#1632	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2472)
#1633	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:848)
#1634	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2481)
#1635	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.os.Handler.dispatchMessage(Handler.java:99)
#1636	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.os.Looper.loop(Looper.java:137)
#1637	03-01 16:12:05.899	10178	E	AndroidRuntime	         at android.app.ActivityThread.main(ActivityThread.java:4424)
#1638	03-01 16:12:05.899	10178	E	AndroidRuntime	         at java.lang.reflect.Method.invokeNative(Native Method)
#1639	03-01 16:12:05.899	10178	E	AndroidRuntime	         at java.lang.reflect.Method.invoke(Method.java:511)
#1640	03-01 16:12:05.899	10178	E	AndroidRuntime	         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
#1641	03-01 16:12:05.899	10178	E	AndroidRuntime	         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
#1642	03-01 16:12:05.899	10178	E	AndroidRuntime	         at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Jayin** [comment]
只有极少数国产手机(联想K2110A)没有处理这个邮箱链接的Intent  无视之
